/* eslint-env jest */
import React from 'react'
import { shallow } from 'enzyme'
import { uniqueId } from 'lodash'
import { relayRendererFactory } from '../relayRendererFactory'

describe('initial state', () => {
  it('is the current environment', () => {
    const customEnvProvider = jest.fn(() => 'custom!')
    const otherEnvProvider = jest.fn(() => 'other!')
    const CustomRelayRenderer = relayRendererFactory(customEnvProvider)
    const OtherCustomRelayRenderer = relayRendererFactory(otherEnvProvider)
    const props = { query: 'query' }

    expect(customEnvProvider).toHaveBeenCalledTimes(1)
    expect(otherEnvProvider).toHaveBeenCalledTimes(1)

    const subject = shallow(<CustomRelayRenderer {...props} />)
    const other = shallow(<OtherCustomRelayRenderer {...props} />)
    expect(subject).toHaveState('relayEnvironment', 'custom!')
    expect(other).toHaveState('relayEnvironment', 'other!')
  })
})

describe('customRelayRendererId', () => {
  it('gives each rendered renderer a unique id', () => {
    const CustomRelayRenderer = relayRendererFactory(() => 1)
    const props = { query: 'query' }
    const subject = shallow(<CustomRelayRenderer {...props} />)
    const other = shallow(<CustomRelayRenderer {...props} />)
    expect(subject.instance().customRelayRendererId).toEqual(1)
    expect(other.instance().customRelayRendererId).toEqual(2)
  })

  it('does not affect other components generated by the factory', () => {
    const CustomRelayRenderer = relayRendererFactory(() => 1)
    const OtherCustomRelayRenderer = relayRendererFactory(() => 1)
    const props = { query: 'query' }
    const subject = shallow(<OtherCustomRelayRenderer {...props} />)
    expect(subject.instance().customRelayRendererId).toEqual(1)
    shallow(<CustomRelayRenderer {...props} />)
    shallow(<CustomRelayRenderer {...props} />)
    const other = shallow(<OtherCustomRelayRenderer {...props} />)
    expect(subject.instance().customRelayRendererId).toEqual(1)
    expect(other.instance().customRelayRendererId).toEqual(2)
  })
})

describe('#getChildContext', () => {
  let subject
  let result

  beforeEach(() => {
    const CustomRelayRenderer = relayRendererFactory(() => 1)
    subject = shallow(<CustomRelayRenderer query='query' />)
    result = subject.instance().getChildContext()
  })

  it('has the relay environment', () => {
    expect(result.relayEnvironment).toEqual(subject.state('relayEnvironment'))
  })

  it('has the refresh relay environment function', () => {
    expect(result.refreshRelayEnvironment).toBeInstanceOf(Function)
    expect(result.refreshRelayEnvironment.name).toEqual('refreshRelayEnvironment')
  })
})

describe('refreshing the relay environment and the component lifecycle', () => {
  let CustomRelayRenderer
  let subject
  let refreshRelayEnvironment
  let counter

  beforeEach(() => {
    let count = 1
    counter = () => count++
    CustomRelayRenderer = relayRendererFactory(counter)
    subject = shallow(<CustomRelayRenderer query='query' />)
    refreshRelayEnvironment = subject.instance().getChildContext().refreshRelayEnvironment
  })

  it('registers new components to receive new relay environments and unregisters them when unmounted', () => {
    const anotherSubject = shallow(<CustomRelayRenderer query='query' />)
    expect(subject).toHaveState('relayEnvironment', 1)
    expect(anotherSubject).toHaveState('relayEnvironment', 1)
    anotherSubject.unmount()
    refreshRelayEnvironment()
    expect(subject).toHaveState('relayEnvironment', 2)
    const yetAnotherSubject = shallow(<CustomRelayRenderer query='query' />)
    expect(yetAnotherSubject).toHaveState('relayEnvironment', 2)
  })

  it('does not affect other components generated by the factory', () => {
    const OtherCustomRelayRenderer = relayRendererFactory(counter)
    const other = shallow(<OtherCustomRelayRenderer query='query' />)
    expect(other).toHaveState('relayEnvironment', 2)
    refreshRelayEnvironment()
    refreshRelayEnvironment()
    expect(subject).toHaveState('relayEnvironment', 4)
    expect(other).toHaveState('relayEnvironment', 2)
    refreshRelayEnvironment()
    expect(subject).toHaveState('relayEnvironment', 5)
    expect(other).toHaveState('relayEnvironment', 2)
  })
})

describe('#render', () => {
  it('renders a relay renderer and passes through all of its props', () => {
    const props = { some: 'props', for: 'testing', query: 'some query' }
    const CustomRelayRenderer = relayRendererFactory(uniqueId)
    const subject = shallow(<CustomRelayRenderer {...props} />)
    expect(subject.find('RelayRenderer').props()).toEqual(props)
  })
})
